# Generated by Django 5.0.6 on 2024-07-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('is_completed', models.BooleanField()),
                ('Task_Assign_Data', models.DateField()),
            ],
        ),
    ]
